name: installer
description: Install APKs via com.android.vending (Play Store)
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 8.1.0
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
